services:
  active-voice:
    build:
      context: .
      dockerfile: ./active-voice/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./active-voice:/opt/active-voice/app:delegated
      - ./active-voice/package.json:/opt/active-voice/package.json
      - ./active-voice/package-lock.json:/opt/active-voice/package-lock.json
      - notused:/opt/active-voice/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused:
