export const painLocationOptions: string[] = [
    'Cabeça',
    'Olho Esquerdo',
    'Olho Direito',
    'Braço Esquerdo Superior',
    'Braço Direito Superior',
    'Perna Esquerda',
    'Perna Direita',
    'Região Facial Direita',
    'Região Facial Esquerda',
    'Região Orbital Direita',
    'Região Orbital Esquerda',
    'Região Frontal',
    'Região Cefálica Esquerda',
    'Região Cefálica Direita',
    'Região Nasal',
    'Mento',
    'Região Auricular Esquerda',
    'Região Auricular Direita',
    'Boca',
    'Região Occipital Esquerda',
    'Região Occipital Direita',
    'Lóbulo Auricular Esquerda',
    'Lóbulo Auricular Direita',
    'Região Esternal',
    'Região Peitoral Esquerda',
    'Região Peitoral Direita',
    'Clavícula Esquerda',
    'Clavícula Direita',
    'Grade Costal Esquerda',
    'Grade Costal Direita',
    'Região Hemi-Abdominal Esquerda',
    'Região Hemi-Abdominal Direita',
    'Região Central Abdómen',
    'Região Púbica Esquerda',
    'Região Púbica Direita',
    'Períneo',
    'Crista Ilíaca Esquerda',
    'Crista Ilíaca Direita',
    'Região Inguinofemoral Esquerda',
    'Região Inguinofemoral Direita',
    'Região Cervical Esquerda',
    'Região Cervical Direita',
    'Região Supraescapular Esquerda',
    'Região Supraescapular Direita',
    'Região Escapular Esquerda',
    'Região Escapular Direita',
    'Região Toráxica Esquerda',
    'Região Toráxica Direita',
    'Região Lombar Esquerda',
    'Região Lombar Direita',
    'Região Nadegueira Esquerda',
    'Região Nadegueira Direita',
    'Coluna', 'Região Cervical',
    'Região Troncantéria Esquerda',
    'Região Troncantéria Direita',
    'Tuberosidade Isquiática Esquerda',
    'Tuberosidade Isquiática Direita',
    'Região Peri-Anal',
    'Região Sarcococcigea',
    'Ombro Esquerdo',
    'Ombro Direito',
    'Região Branquial Esquerda',
    'Região Branquial Direita',
    'Fossa Cubital Esquerda',
    'Fossa Cubital Direita',
    'Face Antebraco Esquerdo',
    'Face Antebraco Direito',
    'Cotovelo Esquerdo',
    'Cotovelo Direito',
    'Face Antebraço Esquerdo',
    'Face Antebraço Direito',
    'Região Coxafemoral Esquerda',
    'Região Coxafemoral Direito',
    'Terço Inferior da Coxa Esquerda',
    'Terço Inferior da Coxa Direita',
    'Joelho Esquerdo', 'Joelho Direito',
    'Terço Superior Esquerdo',
    'Terço Superior Direito',
    'Terço Médio Esquerdo',
    'Terço Médio Direito',
    'Terço Inferior Esquerdo',
    'Terço Inferior Direito',
    'Região Femoral Esquerda',
    'Região Femoral Direita',
    'Fossa Poplitea Esquerda',
    'Fossa Poplitea Direita',
    'Região Gemelar Esquerda',
    'Região Gemelar Direita',
    'Região Maleolar Interna Esquerda',
    'Região Maleolar Interna Direito',
    'Dorso Pé Esquerdo',
    'Dorso Pé Direito',
    'Hálux esquerdo',
    'Hálux Direito',
    'Pé Esquerdo Dedo 1',
    'Pé Direito Dedo 1',
    'Pé Esquerdo Dedo 2',
    'Pé Direito Dedo 2',
    'Pé Esquerdo Dedo 3',
    'Pé Direito Dedo 3',
    'Pé Esquerdo Dedo 4',
    'Pé Direito Dedo 4',
    'Pé Esquerdo Dedo 5',
    'Pé Direito Dedo 5',
    'Região Maleolar Externa Esquerda',
    'Região Maleolar Externa Direita',
    'Calcânio Esquerdo',
    'Calcânio Direito',
    'Região Plantar Esquerdo',
    'Região Plantar Direito',
    'Pé Esquerdo Face Plantar Dedo 1',
    'Pé Direito Face Plantar Dedo 1',
    'Pé Esquerdo Face Plantar Dedo 2',
    'Pé Direito Face Plantar Dedo 2',
    'Pé Esquerdo Face Plantar Dedo 3',
    'Pé Direito Face Plantar Dedo 3',
    'Pé Esquerdo Face Plantar Dedo 4',
    'Pé Direito Face Plantar Dedo 4',
    'Pé Esquerdo Face Plantar Dedo 5',
    'Pé Direito Face Plantar Dedo 5',
    'Região Palmar Esquerda',
    'Região Palmar Direito',
    'Mão Esquerda Dedo 1',
    'Mão Direita Dedo 1',
    'Mão Esquerda Dedo 2',
    'Mão Direita Dedo 2',
    'Mão Esquerda Dedo 3',
    'Mão Direita Dedo 3',
    'Mão Esquerda Dedo 4',
    'Mão Direita Dedo 4',
    'Mão Esquerda Dedo 5',
    'Mão Direita Dedo 5',
    'Dorso Mão Esquerda',
    'Dorso Mão Direita',
    'Dorso Mão Esquerda Dedo 1',
    'Dorso Mão Direita Dedo 1',
    'Dorso Mão Esquerda Dedo 2',
    'Dorso Mão Direita Dedo 2',
    'Dorso Mão Esquerda Dedo 3',
    'Dorso Mão Direita Dedo 3',
    'Dorso Mão Esquerda Dedo 4',
    'Dorso Mão Direita Dedo 4',
    'Dorso Mão Esquerda Dedo 5',
    'Dorso Mão Direita Dedo 5']


const painLocationSynonyms: Record<string, string> = {
    'Cara': 'Região Frontal',
    'Nariz': 'Região Nasal',
    'Ouvido Esquerdo': 'Região Auricular Esquerda',
    'Ouvido Direito': 'Região Auricular Direita',
    'Orelha Esquerda': 'Lóbulo Auricular Esquerda',
    'Orelha Direita': 'Lóbulo Auricular Direita',
    'Peito Esquerda': 'Região Peitoral Esquerda',
    'Peito Direito': 'Região Peitoral Direita',
    'Costelas Esquerdas': 'Grade Costal Esquerda',
    'Costelas Direitas': 'Grade Costal Direita',
    'Abdominais Esquerdos': 'Região Hemi-Abdominal Esquerda',
    'Abdominais Direito': 'Região Hemi-Abdominal Direita',
    'Pescoço': 'Região Cervical',
    'Antebraço Esquerdo': 'Face Antebraco Esquerdo',
    'Antebraço Direito': 'Face Antebraco Direito',
    'Coxa Esquerda': 'Região Femoral Esquerda',
    'Coxa Direita': 'Região Femoral Direita',
    'Gemeo Esquerdo': 'Região Gemelar Esquerda',
    'Gemeo Direito': 'Região Gemelar Direita',
    'Peito do Pé Esquerdo': 'Dorso Pé Esquerdo',
    'Peito do Pé Direito': 'Dorso Pé Direito',
    'Joanetes Esquerdo': 'Hálux esquerdo',
    'Joanetes Direito': 'Hálux Direito',
    'Pé Esquerdo Dedo Grande': 'Pé Esquerdo Dedo 1',
    'Pé Direito Dedo Grande': 'Pé Direito Dedo 1',
    'Pé Esquerdo Dedo Pequenino': 'Pé Esquerdo Dedo 5',
    'Pé Direito Dedo Pequenino': 'Pé Direito Dedo 5',
    'Tornozelo Esquerdo': 'Região Maleolar Externa Esquerda',
    'Tornozelo Direito': 'Região Maleolar Externa Direito',
    'Calcanhar Esquerdo': 'Calcânio Esquerdo',
    'Calcanhar Direito': 'Calcânio Direito',
    'Planta do Pé Esquerdo': 'Região Plantar Esquerdo',
    'Planta do Pé Direito': 'Região Plantar Direito',
    'Polegar Esquerdo': 'Mão Esquerda Dedo 1',
    'Dedo Indicador Esquerdo': 'Mão Esquerda Dedo 2',
    'Dedo do Meio Esquerdo': 'Mão Esquerda Dedo 3',
    'Dedo Anelar Esquerdo': 'Mão Esquerda Dedo 4',
    'Dedo Mindinho Esquerdo': 'Mão Esquerda Dedo 5',
    'Polegar Direito': 'Mão Direita Dedo 1',
    'Dedo Indicador Direito': 'Mão Direita Dedo 2',
    'Dedo do Meio Direito': 'Mão Direito Dedo 3',
    'Dedo Anelar Direito': 'Mão Direito Dedo 4',
    'Dedo Mindinho Direito': 'Mão Direito Dedo 5',
};
